import { CEILING_COVE_OFFSET, WALL_HEIGHT } from './portfolioSceneLayout';

export const PR_REAPER_COVE_CLEARANCE = 0.18;
export const PR_REAPER_DISPLAY_FLOOR_CLEARANCE = 0.42;
export const PR_REAPER_AVAILABLE_LED_SAFE_HEIGHT =
  WALL_HEIGHT - CEILING_COVE_OFFSET;
export const PR_REAPER_SCREEN_TOP_MAX =
  PR_REAPER_AVAILABLE_LED_SAFE_HEIGHT - PR_REAPER_COVE_CLEARANCE;
export const PR_REAPER_SCREEN_HEIGHT = Math.min(
  WALL_HEIGHT * 0.84,
  PR_REAPER_SCREEN_TOP_MAX - PR_REAPER_DISPLAY_FLOOR_CLEARANCE
);
export const PR_REAPER_SCREEN_WIDTH = PR_REAPER_SCREEN_HEIGHT * (9 / 21);
export const PR_REAPER_SCREEN_BOTTOM_Y = PR_REAPER_DISPLAY_FLOOR_CLEARANCE;
export const PR_REAPER_SCREEN_CENTER_Y =
  PR_REAPER_SCREEN_BOTTOM_Y + PR_REAPER_SCREEN_HEIGHT / 2;
export const PR_REAPER_SCREEN_PLANE_Z = 0;
export const PR_REAPER_STREAM_CIRCLE_RADIUS = PR_REAPER_SCREEN_WIDTH * 0.055;
export const PR_REAPER_STREAM_HORIZONTAL_MARGIN =
  PR_REAPER_SCREEN_WIDTH * 0.045;
export const PR_REAPER_STREAM_START_Y =
  PR_REAPER_SCREEN_BOTTOM_Y +
  PR_REAPER_SCREEN_HEIGHT +
  PR_REAPER_STREAM_CIRCLE_RADIUS;
export const PR_REAPER_STREAM_END_Y =
  PR_REAPER_SCREEN_BOTTOM_Y - PR_REAPER_STREAM_CIRCLE_RADIUS;
export const PR_REAPER_STREAM_Z = PR_REAPER_SCREEN_PLANE_Z + 0.018;
export const PR_REAPER_STREAM_DESCENT_DURATION_SECONDS = 5.5;
export const PR_REAPER_STREAM_SPAWN_INTERVAL_MIN_SECONDS = 0.5;
export const PR_REAPER_STREAM_SPAWN_INTERVAL_MAX_SECONDS = 1.5;
export const PR_REAPER_STREAM_MAX_CATCH_UP_SPAWNS = 8;
export const PR_REAPER_STREAM_MAX_DELTA_SECONDS = 5;
export const PR_REAPER_PR_CIRCLE_POOL_CAPACITY =
  Math.ceil(
    PR_REAPER_STREAM_DESCENT_DURATION_SECONDS /
      PR_REAPER_STREAM_SPAWN_INTERVAL_MIN_SECONDS
  ) + PR_REAPER_STREAM_MAX_CATCH_UP_SPAWNS;

export const PR_REAPER_PROJECTOR_HEIGHT = 0.32;
export const PR_REAPER_PROJECTOR_SCREEN_GAP = 0.1;
export const PR_REAPER_PROJECTOR_WIDTH = PR_REAPER_SCREEN_WIDTH * 0.72;
export const PR_REAPER_PROJECTOR_DEPTH = 0.62;
export const PR_REAPER_PROJECTOR_CENTER_Y = PR_REAPER_PROJECTOR_HEIGHT / 2;
export const PR_REAPER_PROJECTOR_CENTER_Z = -0.06;

export const PR_REAPER_MIN_EMITTER_STANDOFF = PR_REAPER_SCREEN_HEIGHT / 2;
export const PR_REAPER_SHOULDER_Y = 0.84;
export const PR_REAPER_ARM_LINK_LENGTH = 0.64;
export const PR_REAPER_TOOL_FORWARD = 0.18;
export const PR_REAPER_EMITTER_LOCAL_Z = 0.06;
export const PR_REAPER_ROBOT_BASE_Z =
  PR_REAPER_MIN_EMITTER_STANDOFF +
  PR_REAPER_ARM_LINK_LENGTH +
  PR_REAPER_TOOL_FORWARD +
  0.08;
export const PR_REAPER_SHOULDER_Z = PR_REAPER_ROBOT_BASE_Z;
export const PR_REAPER_ROBOT_BASE_RADIUS = 0.3;
export const PR_REAPER_ROBOT_BASE_HEIGHT = 0.24;
export const PR_REAPER_YAW_PIVOT = {
  x: 0,
  y: PR_REAPER_ROBOT_BASE_HEIGHT,
  z: PR_REAPER_ROBOT_BASE_Z,
};
export const PR_REAPER_PITCH_PIVOT = { x: 0, y: PR_REAPER_SHOULDER_Y, z: 0 };
export const PR_REAPER_TOOL_FLANGE_OFFSET = {
  x: 0,
  y: 0,
  z: -PR_REAPER_ARM_LINK_LENGTH,
};
export const PR_REAPER_EMITTER_OFFSET = {
  x: 0,
  y: 0,
  z: -(PR_REAPER_TOOL_FORWARD + PR_REAPER_EMITTER_LOCAL_Z),
};
export const PR_REAPER_YAW_LIMITS = { min: -Math.PI / 3, max: Math.PI / 3 };
export const PR_REAPER_PITCH_LIMITS = { min: -Math.PI / 8, max: Math.PI / 5 };
export const PR_REAPER_PARKED_POSE = { yaw: 0, pitch: 0 };
export const PR_REAPER_EMITTER_PARKED_Z =
  PR_REAPER_SHOULDER_Z -
  PR_REAPER_ARM_LINK_LENGTH -
  PR_REAPER_TOOL_FORWARD -
  PR_REAPER_EMITTER_LOCAL_Z;
export const PR_REAPER_SCREEN_TO_EMITTER_STANDOFF =
  PR_REAPER_EMITTER_PARKED_Z - PR_REAPER_SCREEN_PLANE_Z;

export const PR_REAPER_TARGET_PROGRESS_MIN = 0.12;
export const PR_REAPER_TARGET_PROGRESS_MAX = 0.9;
export const PR_REAPER_AIM_TOLERANCE_RADIANS = 0.035;
export const PR_REAPER_AIM_HOLD_SECONDS = 0.04;
export const PR_REAPER_LASER_DURATION_SECONDS = 0.12;
export const PR_REAPER_RECOVER_SECONDS = 0.18;
export const PR_REAPER_ARM_DAMPING = 12;
export const PR_REAPER_PARTICLE_BURST_POOL_CAPACITY = 4;
export const PR_REAPER_PARTICLE_DURATION_MIN_SECONDS = 0.25;
export const PR_REAPER_PARTICLE_DURATION_MAX_SECONDS = 0.5;

export const PR_REAPER_REAR_DEPTH = 0.42;
export const PR_REAPER_FRONT_DEPTH = PR_REAPER_ROBOT_BASE_Z + 0.38;
export const PR_REAPER_FOOTPRINT_DEPTH =
  PR_REAPER_REAR_DEPTH + PR_REAPER_FRONT_DEPTH;
export const PR_REAPER_FOOTPRINT_WIDTH = Math.max(
  PR_REAPER_SCREEN_WIDTH + 0.46,
  2.62
);
export const PR_REAPER_INTENDED_BOUNDS = {
  width: PR_REAPER_FOOTPRINT_WIDTH,
  depth: PR_REAPER_FOOTPRINT_DEPTH,
  height: PR_REAPER_SCREEN_BOTTOM_Y + PR_REAPER_SCREEN_HEIGHT,
};
