import { MathUtils } from 'three';

import { CEILING_COVE_OFFSET, WALL_HEIGHT } from './portfolioSceneLayout';

export const PR_REAPER_COVE_CLEARANCE = 0.18;
export const PR_REAPER_DISPLAY_FLOOR_CLEARANCE = 0.42;
export const PR_REAPER_AVAILABLE_LED_SAFE_HEIGHT =
  WALL_HEIGHT - CEILING_COVE_OFFSET;
export const PR_REAPER_SCREEN_TOP_MAX =
  PR_REAPER_AVAILABLE_LED_SAFE_HEIGHT - PR_REAPER_COVE_CLEARANCE;
export const PR_REAPER_SCREEN_HEIGHT = Math.min(
  WALL_HEIGHT * 0.84,
  PR_REAPER_SCREEN_TOP_MAX - PR_REAPER_DISPLAY_FLOOR_CLEARANCE
);
export const PR_REAPER_SCREEN_WIDTH = PR_REAPER_SCREEN_HEIGHT * (9 / 21);
export const PR_REAPER_SCREEN_BOTTOM_Y = PR_REAPER_DISPLAY_FLOOR_CLEARANCE;
export const PR_REAPER_SCREEN_CENTER_Y =
  PR_REAPER_SCREEN_BOTTOM_Y + PR_REAPER_SCREEN_HEIGHT / 2;
export const PR_REAPER_SCREEN_PLANE_Z = 0;
export const PR_REAPER_SCREEN_TOP_Y =
  PR_REAPER_SCREEN_BOTTOM_Y + PR_REAPER_SCREEN_HEIGHT;

export const PR_REAPER_PROJECTOR_HEIGHT = 0.32;
export const PR_REAPER_PROJECTOR_SCREEN_GAP = 0.1;
export const PR_REAPER_PROJECTOR_WIDTH = PR_REAPER_SCREEN_WIDTH * 0.72;
export const PR_REAPER_PROJECTOR_DEPTH = 0.62;
export const PR_REAPER_PROJECTOR_CENTER_Y = PR_REAPER_PROJECTOR_HEIGHT / 2;
export const PR_REAPER_PROJECTOR_CENTER_Z = -0.06;

export const PR_REAPER_MIN_EMITTER_STANDOFF = PR_REAPER_SCREEN_HEIGHT / 2;
export const PR_REAPER_SHOULDER_Y = 0.84;
export const PR_REAPER_ARM_LINK_LENGTH = 0.64;
export const PR_REAPER_TOOL_FORWARD = 0.18;
export const PR_REAPER_EMITTER_LOCAL_Z = 0.06;
export const PR_REAPER_ROBOT_BASE_Z =
  PR_REAPER_MIN_EMITTER_STANDOFF +
  PR_REAPER_ARM_LINK_LENGTH +
  PR_REAPER_TOOL_FORWARD +
  0.08;
export const PR_REAPER_SHOULDER_Z = PR_REAPER_ROBOT_BASE_Z;
export const PR_REAPER_ROBOT_BASE_RADIUS = 0.34;
export const PR_REAPER_ROBOT_BASE_HEIGHT = 0.3;
export const PR_REAPER_YAW_PIVOT = {
  x: 0,
  y: PR_REAPER_ROBOT_BASE_HEIGHT,
  z: PR_REAPER_ROBOT_BASE_Z,
};
export const PR_REAPER_PITCH_PIVOT = { x: 0, y: PR_REAPER_SHOULDER_Y, z: 0 };
export const PR_REAPER_TOOL_FLANGE_OFFSET = {
  x: 0,
  y: 0,
  z: -PR_REAPER_ARM_LINK_LENGTH,
};
export const PR_REAPER_EMITTER_OFFSET = {
  x: 0,
  y: 0,
  z: -(PR_REAPER_TOOL_FORWARD + PR_REAPER_EMITTER_LOCAL_Z),
};
export const PR_REAPER_YAW_LIMITS = {
  min: -MathUtils.degToRad(42),
  max: MathUtils.degToRad(42),
};
export const PR_REAPER_PITCH_LIMITS = {
  min: MathUtils.degToRad(-28),
  max: MathUtils.degToRad(58),
};
export const PR_REAPER_PARKED_POSE = {
  yaw: 0,
  pitch: MathUtils.degToRad(8),
};

export const PR_REAPER_REAR_DEPTH = 0.42;
export const PR_REAPER_FRONT_DEPTH = PR_REAPER_ROBOT_BASE_Z + 0.38;
export const PR_REAPER_FOOTPRINT_DEPTH =
  PR_REAPER_REAR_DEPTH + PR_REAPER_FRONT_DEPTH;
export const PR_REAPER_FOOTPRINT_WIDTH = Math.max(
  PR_REAPER_SCREEN_WIDTH + 0.46,
  2.62
);
export const PR_REAPER_INTENDED_BOUNDS = {
  width: PR_REAPER_FOOTPRINT_WIDTH,
  depth: PR_REAPER_FOOTPRINT_DEPTH,
  height: PR_REAPER_SCREEN_TOP_Y,
};
