apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "danielsmith.fullname" . }}-build-info
  labels:
    {{- include "danielsmith.labels" . | nindent 4 }}
data:
  build-info.json: |
{{ include "danielsmith.buildInfo.json" . | indent 4 }}
