{{- if .Values.githubMetricsCache.enabled -}}
{{- include "danielsmith.githubMetricsCache.validate" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "danielsmith.fullname" . }}-github-metrics-cache
  labels:
    {{- include "danielsmith.labels" . | nindent 4 }}
data:
  repos.json: |
{{ toPrettyJson .Values.githubMetricsCache.repos | indent 4 }}
  refresh-github-metrics.py: |
{{ .Files.Get "files/refresh-github-metrics.py" | indent 4 }}

{{- end }}
