name: Favicon

on:
  push:
    branches: [main]
    paths:
      - scripts/generate-favicon.ts
      - package.json
      - package-lock.json
      - public/favicon.ico
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Generate favicon
        run: npm run favicon

      - name: Commit updated favicon
        run: |
          if git diff --quiet -- public/favicon.ico; then
            echo "No favicon changes to commit."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/favicon.ico
          git commit -m "🤖 : – Regenerate favicon"
          git push
