name: Favicon

on:
  push:
    branches: [main]
    paths:
      - scripts/generate-favicon.ts
      - package.json
      - package-lock.json
      - public/favicon.ico
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Generate favicon
        run: npm run favicon

      - name: Create pull request with updated favicon
        uses: peter-evans/create-pull-request@v6
        with:
          add-paths: public/favicon.ico
          branch: codex/update-favicon
          commit-message: '🤖 : – Update favicon'
          title: '🤖 : – Update favicon'
          body: |
            what: regenerate favicon.ico from scripts/generate-favicon.ts
            why: keep generated asset in sync with the script output
            how to test: npm run favicon
